easy_admin:
  site_name: Null Training
  entities:
    Workshop:
      class: App\Entity\Workshop
      list:
        fields: ['id', 'enTitle', 'hrTitle', 'active','showOnHomepage', 'createdAt']
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
        fields:
          - { property: 'enTitle', label: 'Title (ENG)' }
          - { property: 'hrTitle', label: 'Title (HR)' }
          - { property: 'enShortIntroduction', label: 'Short intro (ENG)', 'type': 'text' }
          - { property: 'hrShortIntroduction', label: 'Short intro (HR)', 'type': 'text' }
          - { property: 'enDescription', label: 'Description (ENG)' }
          - { property: 'hrDescription', label: 'Description (HR)' }
          - { property: 'active', label: 'Active' }
          - { property: 'showOnHomepage', label: 'Show on homepage' }
    User:
      class: App\Entity\User
      label: Users
    Inquiry:
      class: App\Entity\Inquiry
      label: Inquiries
    Venue:
      class: App\Entity\Venue
      label: Venues
      list:
        fields: ['id', 'name', 'address', 'description', 'city', 'priority', 'additionalInformation', 'createdAt']
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
        fields:
          - { property: 'name', label: 'Name' }
          - { property: 'address', label: 'Address' }
          - { property: 'description', label: 'Description' }
          - { property: 'city', label: 'City' }
          - { property: 'priority', label: 'Priority' }
          - { property: 'additionalInformation', label: 'Additional Information' }
    City:
      class: App\Entity\City
      label: Cities
      list:
        fields: ['id', 'name', 'country', 'priority', 'createdAt']
      form:  # <-- 'form' is applied to both 'new' and 'edit' views
        fields:
          - { property: 'name', label: 'Name' }
          - { property: 'country', label: 'Country' }
          - { property: 'priority', label: 'Priority' }
    Country:
      class: App\Entity\Country
      label: Countries

