
version: '2'

services:

  training-code:
    image: msvrtan/code:0.2.0
    container_name: training-code
    volumes:
      - ./:/var/www

  training-nginx-dev:
    build:
      context: ./etc/docker/nginx-sf4-dev
    container_name: training-nginx-dev
    volumes_from:
      - training-code
    volumes:
      - ./var/logs/dev/nginx/:/var/log/nginx
    ports:
      - "8000:80"
    links:
      - training-php7fpm-dev
      - training-php7fpm-test

  training-php7fpm-dev:
    container_name: training-php7fpm-dev
    image: msvrtan/php7fpm-dev:0.4.1
    shm_size: 256MB
    volumes_from:
      - training-code
    volumes:
      - ./var/logs/dev/php-fpm/:/var/log/php-fpm
    expose:
      - "9000"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: 123
      DATABASE_DRIVER: pdo_mysql
      DATABASE_SERVER_VERSION: 5.7
      DATABASE_HOST: training_mysql_dev
      DATABASE_PORT: 3306
      DATABASE_NAME: training_dev
      DATABASE_USER: root
      DATABASE_PASSWORD: n0p455
      GA_TRACKING: "UA-xxxxxxxx-1"
    links:
      - training-mysql-dev
    extra_hosts:
      - "dev.training.loc:172.17.0.1"
      - "test.training.loc:172.17.0.1"

  training-php7fpm-test:
    container_name: training-php7fpm-test
    image: msvrtan/php7fpm-dev:0.4.1
    shm_size: 256MB
    volumes_from:
      - training-code
    volumes:
      - ./var/logs/test/php-fpm/:/var/log/php-fpm
    expose:
      - "9000"
    environment:
      APP_ENV: test
      APP_DEBUG: 1
      APP_SECRET: 123
      DATABASE_DRIVER: pdo_mysql
      DATABASE_SERVER_VERSION: 5.7
      DATABASE_HOST: training_mysql_dev
      DATABASE_PORT: 3306
      DATABASE_NAME: training_dev
      DATABASE_USER: root
      DATABASE_PASSWORD: n0p455
      GA_TRACKING: "UA-xxxxxxxx-1"
    links:
      - training-mysql-dev
    extra_hosts:
      - "dev.training.loc:172.17.0.1"
      - "test.training.loc:172.17.0.1"
      
  training-mysql-dev:
    image: "mysql:5.7"
    container_name: training_mysql_dev
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: n0p455
      MYSQL_DATABASE: training_dev
      MYSQL_USER: training
      MYSQL_PASSWORD: n0p455

  training-cli:
    container_name: training-cli
    image: msvrtan/workspace-dev:0.5.0
    shm_size: 256MB
    volumes_from:
      - training-code
    links:
      - training-mysql-dev
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: 123
      DATABASE_DRIVER: pdo_mysql
      DATABASE_SERVER_VERSION: 5.7
      DATABASE_HOST: training-mysql-dev
      DATABASE_PORT: 3306
      DATABASE_NAME: training_dev
      DATABASE_USER: root
      DATABASE_PASSWORD: n0p455
      GA_TRACKING: "UA-xxxxxxxx-1"
    extra_hosts:
      - "dev.training.loc:172.17.0.1"
      - "test.training.loc:172.17.0.1"

  training-xdebug:
    container_name: training-xdebug
    image: msvrtan/xdebug-dev:0.4.1
    shm_size: 256MB
    volumes_from:
      - training-code
    links:
      - training-mysql-dev
    environment:
      APP_ENV: test
      APP_DEBUG: 1
      APP_SECRET: 123
      DATABASE_DRIVER: pdo_mysql
      DATABASE_SERVER_VERSION: 5.7
      DATABASE_HOST: training_mysql_dev
      DATABASE_PORT: 3306
      DATABASE_NAME: training_dev
      DATABASE_USER: root
      DATABASE_PASSWORD: n0p455
      GA_TRACKING: "UA-xxxxxxxx-1"
    extra_hosts:
      - "dev.training.loc:172.17.0.1"
      - "test.training.loc:172.17.0.1"
